Fee Reversal
unit-finance/unit-python-sdk pull request #207
Opened 2023-04-23 11:39 UTC by axshani

https://docs.unit.co/fees#reverse-fee

2023-04-24 05:49 UTC, GermanSmoliar commented
@axshani , can you please separate moving to Configuration class to different PR?

2023-04-27 07:34 UTC, GermanSmoliar requested changes
Do we need to add some tests here?

2023-04-27 13:14 UTC, axshani commented on unit/models/fee.py
> +            payload["data"]["attributes"]["idempotencyKey"] = self.tags
fixed that

2023-04-27 13:17 UTC, GermanSmoliar approved these changes

2023-04-27 13:19 UTC, merged