Py-test Pr review additions
unit-finance/unit-python-sdk pull request #274
Opened 2024-04-09 10:01 UTC by stymoshchuk

2024-04-14 18:36 UTC, axshani requested changes

2024-04-14 18:36 UTC, axshani commented on unit/models/returnAch.py
> +class ReturnReceivedAchTransactionRequest(UnitRequest):
good inheritance, now we can use to_payload()

2024-04-14 18:36 UTC, axshani commented on unit/models/statement.py
> +class GetStatementParams(UnitRequest):
you are not wrong, but in this case UnitRequest doesn't help too much. your decision

2024-04-15 12:22 UTC, stymoshchuk commented on unit/models/payment.py
> +        if astra_routine_id:
i will removee

2024-04-15 12:23 UTC, stymoshchuk commented on unit/models/payment.py
> +            payload = super().to_payload("checkPayment", self.relationships)
remove self.rel

2024-04-15 12:29 UTC, stymoshchuk commented on unit/models/payment.py
> +            super().__init__(amount, description, relationships, idempotency_key, tags, None, "pushToCardPayment",
finish it

2024-04-25 13:11 UTC, merged