fix close account method
unit-finance/unit-python-sdk pull request #34
Opened 2021-11-08 18:25 UTC by axshani

I have noticed that close account is not working (thanks to the tests).
I have added type and attributes parameters to the data object.

https://developers.unit.co/deposit-accounts#close-account

2021-11-23 19:22 UTC, Elroie requested changes

2021-11-23 19:22 UTC, Elroie commented on unit/api/account_resource.py
> +        data = {"data": {"type": "accountClose", "attributes": {"reason": reason}}}
to model

2021-11-24 12:07 UTC, axshani commented on unit/api/account_resource.py
> +        data = {"data": {"type": "accountClose", "attributes": {"reason": reason}}}
> to model

fixed!

2021-12-09 16:36 UTC, Elroie approved these changes

2021-12-09 16:36 UTC, merged